name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.*"
      - run: |
          mkdir dist
      - run: |
          sudo apt install fonts-noto
      - run: |
          node -v
          npm install
          node ./index.js
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: create-pdf
      #     path: ./dist/README.pdf
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: deploy
